### ISSUE TITLE
JEOD settings guide/issue or out of the box example errors? 

### ISSUE THREAD

**Issue by edtriccorp** [nasa/jeod#1]
Hello, 

I am running Windows 11 with Windows Subsystem for Linux Ubuntu 18.04 Distribution. I installed NASA Trick and JEOD. Confirmed I can complete NASA Trick examples such as the Cannon Ball tutorial. Then configured the environment variables per JEOD README_jeod.md. Attempted to run SIM_Apollo provided in JEOD. I also repeated the install on a native Ubuntu 18.04 machine and attempted the same run of SIM_Apollo. The error message seems to suggest the error roots from the model setup source. The output is as follows:
![image](https://user-images.githubusercontent.com/3674587/209217829-d8e3bf09-632f-4005-be1f-f470051dae29.png)

Before attempting to debug I just wanted to test my JEOD setup is OK. I am hoping to confirm this is not an out of the box experience for everyone or perhaps just specific to some setup mistake or oversight I have made along the way? Some setup steps I missed for JEOD? I tried another sim example from "/docs/Training/Exercises/Solutions/" folder to run "solved sim" SIM_05 which results in a different errored output as follows:

![image](https://user-images.githubusercontent.com/3674587/209220101-b348b506-ffcc-4a1a-952c-ad2e83a01daf.png)

**Comment by excaliburtb** [comment]
I reproduced the issue for SIM_Apollo. We will fix the sim. 

I also see the same behavior for SIM_05 unless I compile TRICKIFIED. Fortunately, the RUN seems to complete okay despite the MemoryManager errors. It should only impact logging GravityManager variables and checkpoint/restart. 

The good news is, in both cases, you match our behavior.

**Comment by zli0** [comment]
This issue was resolved in [jeod_v5.0.1](https://github.com/nasa/jeod/releases/tag/jeod_v5.0.1) release
