### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [nasa/jeod#4]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [BasicJeodTrickSimInterface](https://github.com/nasa/jeod/blob/464b37b830e04b1e12486947a5db67bd61723394/models/utils/sim_interface/src/trick_sim_interface.cc#L98 "Destructor for BasicJeodTrickSimInterface")
- [JeodMemoryTable](https://github.com/nasa/jeod/blob/464b37b830e04b1e12486947a5db67bd61723394/models/utils/memory/include/memory_table.hh#L167 "Destructor for JeodMemoryTable")
- [ReadTrkCsv](https://github.com/nasa/jeod/blob/464b37b830e04b1e12486947a5db67bd61723394/models/utils/lvlh_frame/verif/SIM_LVLH_Frame/test_code/read_trk_csv.cc#L49 "Destructor for ReadTrkCsv")

**Comment by excaliburtb** [comment]
Thanks for the comment. Captured and will work

**Comment by elfring** [comment]
:thought_balloon: Would you become interested to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability/delete-null-pointer.html "Deletion of unnecessary null pointer checks")?

**Comment by excaliburtb** [comment]
we're always interested in improving our tooling. time is always against us as I'm sure you can understand. I'm aware of the tool but I haven't put it on my TODO list until now. thanks

**Comment by zli0** [comment]
issue addressed in [JEOD v5.1](https://github.com/nasa/jeod/releases/tag/jeod_v5.1)

**Comment by elfring** [comment]
:thought_balloon: I would find an other commit message more helpful for this issue than the information “merge trunk into master for JEOD v5.1 release”.
