### ISSUE TITLE
Slosh model incomplete

### ISSUE THREAD

**Issue by dbrown-osr** [nasa/jeod#5]
The [slosh model](https://github.com/nasa/jeod/tree/main/models/experimental/constraints) appears to be incomplete, and does not have a verification sim or documentation.   We would like to use the slosh model, but it's not usable in its current state.  Please provide a completed the model with an example verification sim that shows how to use it.  If this is not in work, please provide a timeline for completion of the slosh model.

**Comment by zli0** [comment]
As addressed in the release note (README_jeod), the models in the "experimental" directory are experimental models that are not yet rigorously verified and documented up to typical JEOD standards. Users planning to these experimental models should understand the risk associated with them and there are currently no plan for documentation and verification of these models.

[JEOD v5.1 README_jeod](https://github.com/nasa/jeod/blob/jeod_v5.1/README_jeod)
[JEOD v5.0.1 README_jeod](https://github.com/nasa/jeod/blob/jeod_v5.0.1/README_jeod)
