### ISSUE TITLE
Missing Doxygen Documentation

### ISSUE THREAD

**Issue by njohnston-gravitics** [nasa/jeod#6]
We've noticed references in some of the pdf documents to Doxygen documentation in an html directory, however this is missing from the repository.
This portion of the documentation is mentioned in section 3.2.8 of docs/JEOD.pdf and section A.4.1.a of docs/Training/course_text.pdf.
Is it possible for the Doxygen documentation to be added to this repo?
Thanks,
Nic
Edit:  I'm also unable to find the wiki referenced in section 3.2.9 of JEOD.pdf and in the course_text.pdf (pg 205)

**Comment by zli0** [comment]
issue addressed in [JEOD v5.1](https://github.com/nasa/jeod/releases/tag/jeod_v5.1)
