### ISSUE TITLE
Very minor typo in quaternion documentation

### ISSUE THREAD

**Issue by DavidHammen** [nasa/jeod#9]
Line 23 of https://github.com/nasa/jeod/blob/main/models/utils/quaternion/docs/tex/app_prop.tex is

    \vect \omega &\equiv \frac {\framerelvect B \omega I B} \omega \nonumber

The initial `\vect` should be `\vhat`.

**Comment by zli0** [comment]
This issue was resolved in JEOD v5.2 release. https://github.com/nasa/jeod/releases/tag/jeod_v5.2
